
import { Project, ProjectStatus, Department, TeamMember } from './types';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'DEPT-1', name: '戰略指揮部', color: '#6366f1', manager: '總經理' },
  { id: 'DEPT-2', name: '人事行政部', color: '#64748b', manager: '行政主管' },
  { id: 'DEPT-3', name: '財務部', color: '#0284c7', manager: '財務主管' },
  { id: 'DEPT-4', name: '生活品質 第一工程部', color: '#16a34a', manager: '工務主管' },
  { id: 'DEPT-5', name: '品質管理部', color: '#8b5cf6', manager: '品管主管' },
  { id: 'DEPT-6', name: '業務部', color: '#ea580c', manager: '業務經理' },
  { id: 'DEPT-7', name: '行銷部', color: '#ec4899', manager: '行銷經理' },
  { id: 'DEPT-8', name: '傑凱工程 第三工程部', color: '#0ea5e9', manager: '工務主管' }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'BNI2024001',
    departmentId: 'DEPT-6',
    name: '桃園至善街290號防水工程',
    category: '防水工程',
    source: 'BNI',
    client: '冠亨商設計',
    referrer: '舊客介紹',
    manager: '陳信寬',
    startDate: '2024-01-05',
    endDate: '2024-03-05',
    createdDate: '2024-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.COMPLETED,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'BNI2025002',
    departmentId: 'DEPT-6',
    name: '桃園龜山民安街11號防水工程',
    category: '防水工程',
    source: 'BNI',
    client: '璇凱伯修',
    referrer: '網站預約',
    manager: '陳文凱',
    startDate: '2025-01-05',
    endDate: '2025-03-10',
    createdDate: '2025-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.COMPLETED,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'JW2601003',
    departmentId: 'DEPT-6',
    name: '樹林區三龍街24巷16號國為海砂屋補強工程',
    category: '補強工程',
    source: 'JW',
    client: '邱金龍',
    referrer: '',
    manager: '余家豪',
    startDate: '2026-01-05',
    endDate: '2026-04-15',
    createdDate: '2026-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.NEGOTIATING,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'BNI2601004',
    departmentId: 'DEPT-6',
    name: '光復北路190巷40號章省予大樓管線修復工程',
    category: '水電機電',
    source: 'BNI',
    client: '章省予',
    referrer: '',
    manager: '余家豪',
    startDate: '2026-01-05',
    endDate: '',
    createdDate: '2026-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.NEGOTIATING,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'OC2601005',
    departmentId: 'DEPT-6',
    name: '光復南路住宅電力系統更新工程',
    category: '水電機電',
    source: '網路客',
    client: '光復南路業主',
    referrer: '',
    manager: '郭俊宏',
    startDate: '2026-01-05',
    endDate: '',
    createdDate: '2026-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.NEGOTIATING,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'CORP2601002',
    departmentId: 'DEPT-6',
    name: '台中商業辦公室擴建',
    category: '室內裝修',
    source: '企業',
    client: '科技公司',
    referrer: '舊客介紹',
    manager: '林靜宜',
    startDate: '2026-02-15',
    endDate: '2026-08-20',
    createdDate: '2026-01-20',
    budget: 8800000,
    spent: 2100000,
    progress: 15,
    status: ProjectStatus.CONSTRUCTING,
    tasks: [],
    phases: [],
    financials: { labor: 25, material: 55, subcontractor: 15, other: 5 }
  }
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'JK001',
    employeeId: 'JK001',
    name: '陳信寬',
    role: '工務主管',
    systemRole: 'DeptAdmin',
    departmentId: 'DEPT-4',
    email: 'k@example.com',
    phone: '0900000001',
    status: 'Available',
    activeProjectsCount: 3,
    avatar: 'https://ui-avatars.com/api/?name=陳信寬&background=0D8ABC&color=fff',
    specialty: ['防水', '結構補強'],
    salaryType: 'monthly',
    monthlySalary: 80000,
    workDaysPerWeek: 5,
    lunchBonus: 2400,
    insuranceBurdenRate: 0,
    joinDate: '2020-01-01',
    workStartTime: '09:00',
    workEndTime: '18:00',
    laborFee: 1000,
    healthFee: 500
  },
  {
    id: 'JK002',
    employeeId: 'JK002',
    name: '李小龍',
    role: '現場工程師',
    systemRole: 'Staff',
    departmentId: 'DEPT-4',
    email: 'lee@example.com',
    phone: '0900000002',
    status: 'Available',
    activeProjectsCount: 1,
    avatar: 'https://ui-avatars.com/api/?name=李小龍&background=random',
    specialty: ['繩索技術', '外牆清洗'],
    salaryType: 'daily',
    dailyRate: 2500,
    workDaysPerWeek: 5,
    lunchBonus: 1500,
    ropeLicenseLevel: 'L1',
    joinDate: '2023-05-01',
    workStartTime: '08:00',
    workEndTime: '17:00'
  },
  {
    id: 'JK003',
    employeeId: 'JK003',
    name: '王四天',
    role: '設計師',
    systemRole: 'Staff',
    departmentId: 'DEPT-4',
    email: 'wang@example.com',
    phone: '0900000003',
    status: 'Available',
    activeProjectsCount: 2,
    avatar: 'https://ui-avatars.com/api/?name=王四天&background=random',
    specialty: ['室內設計'],
    salaryType: 'monthly',
    monthlySalary: 45000,
    workDaysPerWeek: 4,
    lunchBonus: 2000,
    insuranceBurdenRate: 15,
    joinDate: '2024-02-01',
    workStartTime: '09:00',
    workEndTime: '18:00'
  }
];
